### ISSUE TITLE
no "demName" element in workflow

### ISSUE THREAD

**Issue by mitkin** [johntruckenbrodt/pyroSAR#101]
Hi,

Excited to try out pyroSAR, but quickstart from the docs throws me an error:

```
Traceback (most recent call last):
  File ".\testpyro.py", line 25, in <module>
    gpt('outname_proc.xml')
  File "C:\Users\mikhail\AppData\Roaming\Python\Python38\site-packages\pyroSAR\snap\auxil.py", line 239, in gpt
    dem_name = workflow.tree.find('.//demName').text
AttributeError: 'NoneType' object has no attribute 'text'
```

I am working with sea ice so actually need no DEM.
The script is rather simple:

```
from pyroSAR.snap.auxil import parse_recipe, parse_node
from pyroSAR.snap.auxil import gpt

workflow = parse_recipe('blank')

read = parse_node('Read')
read.parameters['file'] = 'S1B_EW_GRDM_1SDH_20191209T055740_20191209T055840_019284_02468E_B6F0.zip'
read.parameters['formatName'] = 'SENTINEL-1'
workflow.insert_node(read)

tnr = parse_node('ThermalNoiseRemoval')
workflow.insert_node(tnr, before=read.id)
tnr.parameters['selectedPolarisations'] = ['HH']

write = parse_node('Write')
write.parameters['file'] = 'outname'
write.parameters['formatName'] = 'BEAM-DIMAP'
workflow.insert_node(write, before=tnr.id)

workflow.write('outname_proc')
gpt('outname_proc.xml')
```

Running on Windows 10x64. Any ideas for a fix?
pyroSAR from PyPI
Snap v7.0
python 3.8

**Comment by johntruckenbrodt** [comment]
Hi @mitkin,
thanks a lot for reporting this issue.
there was a bug in function `gpt` which is now fixed with commit 713987c.
I will distribute a bugfix release 0.10.2 in the coming days, until then you can install the current master using [git](https://git-scm.com/downloads):
```sh
python3 -m pip install git+https://github.com/johntruckenbrodt/pyroSAR
```
Cheers,
John

**Comment by vpolimenov** [comment]
Hi @johntruckenbrodt,
Is there an update on the new release? 

Thanks :)

**Comment by johntruckenbrodt** [comment]
Hi @vpolimenov,
damn, I forgot about this. I am currently busy with wrapping everything up for version 0.11.  
This should be out some time next week.
Cheers, John

**Comment by johntruckenbrodt** [comment]
Hi @vpolimenov version 0.11 is now released. Cheers
