### ISSUE TITLE
Consider removing progress bar, or allow disabling

### ISSUE THREAD

**Issue by matthewhanson** [johntruckenbrodt/pyroSAR#105]
The progress bar doesn't seem to be reporting progress very well, and I'm not sure it adds much.   It seems to take over stdout and so can interfere when trying to debug.

Progress bars are good for one use case - someone running the code at the command line and looking at the output.  Once you start running in scripts and logging output, or scaling into the cloud as I'm attempting, it's a major nuisance.   At least having a way to disable it and not affect stdout/stderr would be nice.

**Comment by johntruckenbrodt** [comment]
I fully agree, thanks for the tip. Most of the functionality that offers a progress bar already has a parameter to disable it. With the last two commits, 949381e and b35f005, this is now be the case for all.

**Comment by matthewhanson** [comment]
great, thanks for the update @johntruckenbrodt !
