### ISSUE TITLE
Suggestion: include/exclude steps in pyroSAR.snap.util.geocode

### ISSUE THREAD

**Issue by dbazzett** [johntruckenbrodt/pyroSAR#106]
Hello All,
I'm new to pyroSAR, so sorry if this issue has been addressed. For the S1 processing I'm doing, I only need certain steps included in the pyroSAR.snap.util.geocode function. Could this function include True/False options for Multilook, and Terrain-Correction? I don't need these features and it would speed up the processing time. (I'm trying to set up batch scripting and xml files anyhow.)

_searching for new POE files
https://qc.sentinel1.eo.esa.int/api/v1/?product_type=AUX_POEORB&validity_stop__lte=2019-09-12T22:50:46&validity_start__gte=2019-09-10T22:50:46&sentinel1__mission=S1A
unpacking scene
removing border noise..
border noise removal not necessary for IPF version 3.1
executing node sequences..
Subset
ThermalNoiseRemoval
Apply-Orbit-File
Calibration
Multilook
Terrain-Correction
LinearToFromdB
done_

**Comment by johntruckenbrodt** [comment]
Hi @dbazzett,

so far this has not been addressed as I considered both steps, `Multilook` and `Terrain-Correction`, as essential in the workflow. This of course depends on the use case. They are currently contained in the [base workflow](https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/snap/recipes/base.xml), which is parsed by geocode [here](https://github.com/johntruckenbrodt/pyroSAR/blob/427bd4d68a7d954cd834828a68c05c521677ddbb/pyroSAR/snap/util.py#L212).  
Sure, they could be made optional by some True/False parameter. However, `Multilook` is needed for resampling to the target resolution and is only done if the target resolution does not match the original scene resolution. `Terrain-Correction` is essentially the geocoding step and making this optional would be a little contradictory in a function called `geocode`. Although I have been thinking of renaming the function to something more generic for a longer time.  
Can you maybe share an example of what workflow you have in mind?

Cheers,
John

**Comment by dbazzett** [comment]
Hello @johntruckenbrodt,
I suppose terrain-correction is the only feature I want to disable in the workflow - I would use the other features. I'm trying to research ocean imagery and the ocean data is masked in terrain-correction (I believe its controlled by this xml line -nodataValueAtSea-true-/nodataValueAtSea-). It would be helpful for me to bypass this step to keep the ocean data in the image.

<img width="471" alt="SAR" src="https://user-images.githubusercontent.com/44247712/74371183-61dced80-4da6-11ea-838f-a546c0a2990b.png">

**Comment by johntruckenbrodt** [comment]
Ah, Atlantic City. Are you using an external DEM?  
With SRTM 1Sec (`geocode`'s default) my image looks like this:
![S1A__IW___A_20190911T225046_VV_tnr_bnr_Orb_Cal_ML_TC_dB_nodataValueAtSea](https://user-images.githubusercontent.com/18419439/74513004-d4b2a980-4f09-11ea-8e9e-3b07f221ee3a.png)
I have disabled the sea value masking as suggested by you and now the image looks like this:  
![S1A__IW___A_20190911T225046_VV_tnr_bnr_Orb_Cal_ML_TC_dB](https://user-images.githubusercontent.com/18419439/74513063-fca20d00-4f09-11ea-8dc1-65f09a60b3e6.png)
How about I just add a new parameter `nodataValueAtSea` to the geocode function?

**Comment by dbazzett** [comment]
Yes, that would resolve my issue.

**Comment by johntruckenbrodt** [comment]
Okay, done. This is now part of the current master branch as of commit b48d8ae. Thanks a lot for helping to improve pyroSAR!
