### ISSUE TITLE
add also float into custom fields?

### ISSUE THREAD

**Issue by Aranil** [johntruckenbrodt/pyroSAR#114]
https://github.com/johntruckenbrodt/pyroSAR/blob/8d94ca48a560d966a7d4365d25418197eac8d3d6/pyroSAR/drivers.py#L1685

**Comment by johntruckenbrodt** [comment]
Hi @Aranil,
please provide more information about this issue. In its current state the purpose is not clear and I will eventually close it.
Cheers,
John
