### ISSUE TITLE
Alignment to standard grid

### ISSUE THREAD

**Issue by aleny91** [johntruckenbrodt/pyroSAR#116]
Is it possible to add in the geocode function a new parameter to set true/false `<alignToStandardGrid></alignToStandardGrid>` in the Terrain-Correction node?

**Comment by johntruckenbrodt** [comment]
Hi @aleny91,
thanks for the suggestion. This is now included with commit 9d0826d.
Just for future reference, [here](https://forum.step.esa.int/t/how-can-i-snap-outputs-of-terrain-correction-to-a-given-grid/1750) is some more information about this.
I am closing this for now, feel free to reopen if there are issues related to this.
Cheers,
John
