### ISSUE TITLE
libspatialite conflict on Windows

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#117]
Currently it is not possible to use the [Archive.insert](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.drivers.Archive.insert) functionality when pyroSAR was installed via conda.
The conda-forge package libspatialite for Windows does not come with the needed `mod_spatialite.dll` for loading spatialite as SQLite extension. This is described in this issue [here](https://github.com/conda-forge/libspatialite-feedstock/issues/49).
For this reason, pyroSAR's geospatial backend [spatialist](https://github.com/johntruckenbrodt/spatialist) comes with the [mod_spatialite bundle](https://github.com/johntruckenbrodt/spatialist/tree/master/spatialist/pkgs/mod_spatialite), which is stored under `$HOME/.spatialist` upon installation.
Since `mod_spatialite.dll` is not present in the conda installation, this custom spatialist bundle is used internally by pyroSAR.
However, the custom bundle conflicts with the conda installation so that the database can be created, but ingesting scenes fails.
A current workaround is to install pyroSAR+spatialist with pip instead of conda into the conda environment:

```
conda create --name test gdal
conda activate test
python -m pip install pyroSAR
```
This way the conda package libspatialite is not installed and cannot conflict with spatialist's custom mod_spatialite bundle.

**Comment by MarkusZehner** [comment]
Hi John, when trying to merge your master branch into #110 we ran into an error with drivers.Archive.__load_libspatialite where the connection record argument was missing. 

This was resolved by just reverting the drivers.py file (although there was no apparent difference when calling the method).
The error was present in MacOs and Win10 and also with the normal pyroSAR version from pip.

Here the error message, maybe that helps:

`(RCM_py_3_6) MacBook-Air:xx_01 markuszehner$ python downloader.py 
Traceback (most recent call last):
  File "downloader.py", line 72, in <module>
    downloader()
  File "downloader.py", line 60, in downloader
    rcmarchive = db.RCMArchive(os.path.join('RCM_lin_test'))
  File "/Users/markuszehner/miniconda3/envs/RCM_py_3_6/lib/python3.6/site-packages/rcm_archive/RCM_DB.py", line 38, in __init__
    rcm_archive = Archive(dbfile=path, **args)
  File "/Users/markuszehner/miniconda3/envs/RCM_py_3_6/lib/python3.6/site-packages/pyroSAR/drivers.py", line 1692, in __init__
    self.conn = self.engine.connect()
[...]
  File "/Users/markuszehner/miniconda3/envs/RCM_py_3_6/lib/python3.6/site-packages/sqlalchemy/event/attr.py", line 322, in __call__
    fn(*args, **kw)
TypeError: __load_spatialite() missing 1 required positional argument: 'connection_record'`

cheers!

**Comment by johntruckenbrodt** [comment]
Hi Markus, I am not sure I understand this. The `connection_record` argument is needed for calling `sqlalchemy.event.listen` in this line of `Archive.__init__`:
```Python
listen(target=self.engine, identifier='connect', fn=self.__load_spatialite)
```
It is part of the master branch [here](https://github.com/johntruckenbrodt/pyroSAR/blob/4693fc99dadaf9e3293367715b1b3373dd06fd44/pyroSAR/drivers.py#L1750) and is not marked as difference in the PR. Where exactly is it missing?

**Comment by MarkusZehner** [comment]
Nevermind, i did a mistake when merging, leaving self as argument in the now static method load_spatialite

**Comment by johntruckenbrodt** [comment]
This is now fixed with the release of [libspatialite](https://anaconda.org/conda-forge/libspatialite) 5.0.0. The requirement of package [spatialist](https://github.com/johntruckenbrodt/spatialist) (which is a dependency of pyroSAR) has been updated accordingly in conda-forge/spatialist-feedstock#4. Updating spatialist to the latest build of version 0.6 will fix this issue for pyroSAR.
