### ISSUE TITLE
[snap.geocode] error in splitting workflows with export_extra

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#119]
The following currently causes an error:
```python
from pyroSAR.snap import geocode

geocode(infile=scene, outdir=outdir, 
        export_extra=['localIncidenceAngle'])
```
which is related to a bug in splitting workflows with multiple `Write` nodes, one for writing the extra product from `Terrain-Correction` via argument `export_extra` and one for writing the final backscatter product after dB scaling.  

Until this is fixed, a workaround is to increase the number of nodes to be executed in a single workflow:
```python
geocode(infile=scene, outdir=outdir, 
        export_extra=['localIncidenceAngle'],
        groupsize=2)
```
This causes both write nodes to be in a single sub-workflow thus preventing a source node confusion in function [snap.auxil.split](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.snap.auxil.split).

For more details on workflow splitting, see the [SNAP API](https://pyrosar.readthedocs.io/en/latest/general/snap.html) documentation.

**Comment by corsima** [comment]
Just a note: commenting some lines of code worked for me but I am not into the code to say if this break something else. See https://github.com/johntruckenbrodt/pyroSAR/pull/121
