### ISSUE TITLE
Sentinel 1: Reported projection doesn't match coordinate ordering

### ISSUE THREAD

**Issue by system123** [johntruckenbrodt/pyroSAR#136]
Using PyroSAR (master branch).

When loading a Sentinel 1 scene, and running `identify` on it it reports that the projection, and thus the coordinates of the scene footprint are in the standard long/lat format. However, upon inspecting the coordinates, they are in fact in lat/long. 

```
>>> f="/Users/lloyd/Downloads/CapeTownSouthAfrica/S1A_IW_GRDH_1SDV_20210215T172550_20210215T172615_036603_044CDD_F00F.zip"
>>> s=ps.identify(f)
>>> print(s)
pyroSAR ID object of type SAFE
acquisition_mode: IW
cycleNumber: 223
frameNumber: 281821
lines: 16877
orbit: A
orbitNumber_abs: 36603
orbitNumber_rel: 131
polarizations: ['VV', 'VH']
product: GRD
projection: +proj=longlat +datum=WGS84 +no_defs
samples: 25819
sensor: S1A
spacing: (10.0, 10.0)
start: 20210215T172550
stop: 20210215T172615

>>> s.meta['coordinates']
[(-34.062317, 18.26063), (-33.419899, 20.938499), (-34.899975, 21.460228), (-35.553223, 18.738091)]
```

**Comment by johntruckenbrodt** [comment]
Oh. You're right. I never thought much about the convention in this list of coordinates but I fully agree, it should be in line with the CRS description. As the `s.meta['coordinates']` content must be identical for all SAR driver classes this might take a moment to adjust. I don't have the time to get to it right away but it won't be long.  
For the time being here is some more code related to this (in case you haven't discovered it yet):
```Python
from pyroSAR import identify

scene = 'S1A_IW_GRDH_1SDV_20210215T172550_20210215T172615_036603_044CDD_F00F.zip'

id = identify(scene)

print(id.meta['coordinates'])
print(id.getCorners())

with id.bbox() as box:
    print(box.convert2wkt(set3D=False))
```

**Comment by system123** [comment]
Great, I just came across that now but the `convert2wkt` is pretty helpful in getting this into a Shapely polygon.
