### ISSUE TITLE
Wrong synthax in manuals (readthedocs)

### ISSUE THREAD

**Issue by florianbeyer** [johntruckenbrodt/pyroSAR#138]
The second approach to retrieve OSV files, decribed in the file:
`pyroSAR/docs/general/OSV.rst`
is incorrect.

```
from pyroSAR import identify
scene = 'S1A_IW_GRDH_1SDV_20180101T170648_20180101T170713_019964_021FFD_DA78.zip'
id = identify(scene)
id.getOSV(outdir='/path/to/osvdir', osvType='POE', returnMatch=True)
print(match)
```

1. the function getOSV has no "outdir=" (I guess it should be "osvdir=")
2. there is no variable which is named `match`

**Comment by johntruckenbrodt** [comment]
Hi @florianbeyer. Thanks a lot for the report! This is now fixed with commit 4c22447 and the docs have been rebuilt accordingly.
