### ISSUE TITLE
SNAP Geocode Terrain-Flattening error over ocean swaths

### ISSUE THREAD

**Issue by BenMueller** [johntruckenbrodt/pyroSAR#146]
- which operating system are you using?  
Debian 11
- which environment is pyroSAR running in?  
System install (yes, I know, I should be running a `venv` or similar)
- which version of pyroSAR are you using?  
Installed via pip
-  which function of pyroSAR did you call with which parameters?  
The snap variant of `geocode`
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
Latest of Snap (IIRC 8.0.x or similar)
- the full error message
(see below)

Hey all,
I'm having a somewhat similar issue to #127 (imagery over ocean failing at `Terrain-Flattening` step with `geocode`) and was wondering if it's related. I've included a short traceback below:
```
File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/snap/util.py", line 627, in geocode
    gpt(wf_name, groups=groups, cleanup=cleanup,
  File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/snap/auxil.py", line 367, in gpt
    execute(sub, cleanup=cleanup, gpt_exceptions=gpt_exceptions, gpt_args=gpt_args)
  File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/snap/auxil.py", line 264, in execute
    os.remove(outname)
FileNotFoundError: [Errno 2] No such file or directory: 'out/S1A__EW___D_20210606T034046_NR_Orb_Cal_TF_TC_dB/tmp/S1A_EW_GRDM_1SDH_20210606T034046_20210606T034146_038214_048284_4C6C_tmp4.dim'
```
With the particular segment/swath of the image totally open ocean.

If related- would a variant of the code posted in the previous issue allow me to use `Range Doppler Terrain-Correction` on the land-segments of the capture, but `Ellipsoid-Correction-GG` over the ocean segments? If I'm just doing something obviously wrong, feel free to call me out- I'm relatively new to pyroSAR! :laughing: 

Thanks!

**Comment by johntruckenbrodt** [comment]
Hi @BenMueller I guess you are referring to `Terrain-Correction` (geocoding) rather than `Terrain-Flattening` (radiometric correction of terrain) right? You could try running `snap.geocode` with `terrainFlattening=False` and `nodataValueAtSea=False`. This will do the regular Range-Doppler geocoding. I am not sure though if it will work because the DEM does of course not cover the whole image. I think if it doesn't you can either just use `Ellipsoid-Correction-GG` (likely with similar accuracy) or create your own "external" DEM where you use the DEM wherever there is data and fill the gaps with ellipsoid surface heights. See [pyroSAR.auxdata](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#module-pyroSAR.auxdata) for DEM tools. If you end up finding a good way of how to do the ellipsoid gap filling this could be an interesting extension of these functions.

**Comment by BenMueller** [comment]
I'd have to replicate to check, but IIRC running with `terraignFlattening=False` didn't work, but I wasn't aware of the `nodataValueAtSea` parameter at the time.

Agreed, if I end up figuring out a working implementation I'll post back here and (if it requires creating an external DEM) see if I can get a working implementation pushed upstream here. Currently only working on this part-time though so that may take some time.

**Comment by mbednarek360** [comment]
Any updates on this? I'm having the same issue over areas that previously worked without error. Neither disabling terrain flattening nor the `nodataValueAtSea` variable made any effect.

This is the line that fails:
```python
geocode(infile=scene, outdir='./temp/', tr=int(sys.argv[3]), 
    nodataValueAtSea=False, scaling='db', 
    removeS1ThermalNoise=True, 
    demResamplingMethod='BISINC_21_POINT_INTERPOLATION',
    terrainFlattening=True, allow_RES_OSV=True, 
    speckleFilter='Refined Lee', shapefile=shp, cleanup=True)     
```
It errors:
```
File "/usr/lib/python3.9/site-packages/pyroSAR/snap/util.py", line 666, in geocode
    gpt(wf_name, groups=groups, cleanup=cleanup,
  File "/usr/lib/python3.9/site-packages/pyroSAR/snap/auxil.py", line 381, in gpt
    execute(sub, cleanup=cleanup, gpt_exceptions=gpt_exceptions, gpt_args=gpt_args)
  File "/usr/lib/python3.9/site-packages/pyroSAR/snap/auxil.py", line 278, in execute
    os.remove(outname)
FileNotFoundError: [Errno 2] No such file or directory: './temp/S1A__IW___A_20210512T005628_NR_Orb_Cal_TF_Spk_TC_dB/tmp/S1A_IW_GRDH_1SDV_20210512T00
5628_20210512T005653_037848_047788_7D1B_tmp3.dim'
```
Any advice would be appreciated, thanks!

**Comment by johntruckenbrodt** [comment]
The `pyroSAR.snap.geocode` function can process images over ocean using the fully global `GETASSE30` DEM. See issue #127.
