### ISSUE TITLE
't_srs' not recognized in geocode call

### ISSUE THREAD

**Issue by davedavemckay** [johntruckenbrodt/pyroSAR#147]
- which operating system are you using?  
RHEL 8.1
- which environment is pyroSAR running in?  
miniconda3
- which version of pyroSAR are you using?  
0.12.1             pyhd8ed1ab_0    conda-forge
-  which function of pyroSAR did you call with which parameters?  
geocode(scene, outdir='%s' % (path2pyrosar),
                    t_srs=27700, tr=10, scaling='dB',
                    polarizations='all', geocoding_type='Range-Doppler',
                    removeS1BorderNoise=True, removeS1BorderNoiseMethod='pyroSAR',
                    removeS1ThermalNoise=True, terrainFlattening=True,
                    externalDEMFile=dem_file, externalDEMNoDataValue=dem_ndv,
                    externalDEMApplyEGM=True, speckleFilter=False,
                    refarea='gamma0', shapefile=granule_shp,
                    alignToStandardGrid = True, standardGridOriginX = origin[0],
                    standardGridOriginY = origin[1])
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
SNAP Sentinel-1 ToolBox 8.0.4
GDAL 3.0.0
PROJ 6.0.0 (also tried PROJ 8.0.0)
- the full error message
format of parameter 't_srs' not recognized

Hi, I don't know if this error is from pyroSAR, SNAP or PROJ - I suspect PROJ. I have tried a proj4 string as t_srs ("+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs") however the same error is reported.

Any advice gratefully received!

**Comment by davedavemckay** [comment]
I managed to get a little more info on the error:
crsIn not recognized; must be of type WKT, PROJ4 or EPSG
  was: "EPSG:27700" of type str

**Comment by johntruckenbrodt** [comment]
Thanks for reaching out @davedavemckay. This looks a lot like what's been reported in issue #126. Could you have a look whether you can get around it with using the latest master branch of [spatialist](https://github.com/johntruckenbrodt/spatialist)?  
I'll try to publish a new version of that library asap.

**Comment by davedavemckay** [comment]
Thanks, John. It is the same as #126
