### ISSUE TITLE
`dem_autocreate` having issues with Spatialist's `getProjection`

### ISSUE THREAD

**Issue by BenMueller** [johntruckenbrodt/pyroSAR#148]
- which operating system are you using?  
Debian 11
- which environment is pyroSAR running in?  
System python install
- which version of pyroSAR are you using?  
installed via Pip
-  which function of pyroSAR did you call with which parameters? 
`dem_autocreate(<geojson>, 'SRTM 1Sec HGT', 'temp.tif')`
- the full error message

Hey everyone,

Going through some of the Readthedocs tutorials and having some issue with the `dem_autocreate` function. Seems it either isn't able to import `getProjection` properly from `spatialist` or the input data is getting mistyped; is this just an issue with my config or can anyone else replicate? Tried pulling latest spatialist from Github (0.7-ish prerelease I think?) and the error is the same.

Thanks!

```collecting DEM tiles
Traceback (most recent call last):
<cut>
  File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/gamma/dem.py", line 245, in dem_autocreate
    dem_autoload([geometry], demType, vrt=vrt, username=username,
  File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/auxdata.py", line 147, in dem_autoload
    with DEMHandler(geometries) as handler:
  File "/home/bmueller/.local/lib/python3.9/site-packages/pyroSAR/auxdata.py", line 251, in __init__
    if geometry.getProjection('epsg') != 4326:
AttributeError: 'list' object has no attribute 'getProjection'```

**Comment by johntruckenbrodt** [comment]
Are you passing the name of the geojson file as input? The function [dem_autocreate](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.gamma.dem.dem_autocreate) needs a [Vector](https://spatialist.readthedocs.io/en/latest/spatialist.html#vector-class) object:
```Python
from spatialist import Vector
from pyroSAR.gamma.dem import dem_autocreate

with Vector(<geojson>) as geom:
    dem_autocreate(geom, 'SRTM 1Sec HGT', 'temp.tif')
```

**Comment by johntruckenbrodt** [comment]
@BenMueller is this still a thing?

**Comment by johntruckenbrodt** [comment]
Closing this for now. Feel free to reopen if necessary.
