### ISSUE TITLE
Full offline usage with pyroSAR.snap.geocode()

### ISSUE THREAD

**Issue by davedavemckay** [johntruckenbrodt/pyroSAR#149]
Hi @johntruckenbrodt,
I'm using pyroSAR and snap on a system that is strictly offline during processing. The code I'm using was written by a colleague (I'm the software engineer, *not* the geoscientist!!) and works on a system that does have an internest connection. However I'm struggling to get the code to avoid attempting any searching or downloading of files. (I have a version of the code that I do allow to go online, with which I've predownloaded all OSV files required.)

Having read [Handling of Orbit State Vector Files](https://pyrosar.readthedocs.io/en/latest/general/OSV.html#handling-of-orbit-state-vector-files) and looked around the source code, I can see that this use case is accounted for in ID.getOSV() with the useLocal=True boolean. However, when using pyroSAR.snap.geocode(), "searching for new POE files" is printed before an HTTP connection error.  To my understanding , this must mean there's a call to pyroSAR.auxil.catch() somewhere.

If there a way to effectively turn off the check for new POE files? Perhaps the pyroSAR/SNAP system isn't seeing my stored files for some reason? -> Perhaps it's a path!!

Any help or ideas appreciated!

**Comment by johntruckenbrodt** [comment]
Hi @davedavemckay. In general offline processing should be possible. OSV files, DEM tiles and the EGM96-WGS84 height conversion file can all be downloaded with pyroSAR so that SNAP does not attempt to do it. Does the following work (with an arbitrary scene):
```Python
from pyroSAR import identify

scene = 'S1A_IW_GRDH_1SDV_20180101T170648_20180101T170713_019964_021FFD_DA78.zip'

id = identify(scene)

id.getOSV()
```

Repeated runs should not try to search for files and print this message. If not then what code distribution are you using?

**Comment by davedavemckay** [comment]
Hi @johntruckenbrodt, thanks - this helped me figure out that, due to my SNAP setup, there was a mismatch between where pyroSAR downloads data (~/.snap/auxdata) and where SNAP was trying to read it from (an external drive). I've now returned all SNAP settings (in the snap/etc/ files) to default and added symlinks from ~/.snap to the external drive. All working.
TL:DR it was a path. Definitely ordering that t-shirt.
Thanks!

**Comment by johntruckenbrodt** [comment]
Great! Good to know that the SNAP settings work, they used to be ignored.
