### ISSUE TITLE
no data value of layover-shadow mask should not be 0 

### ISSUE THREAD

**Issue by peterfriedl** [johntruckenbrodt/pyroSAR#173]
- which operating system are you using?  
Ubuntu 20.04.2 LTS
- which environment is pyroSAR running in?  
system-wide Python installation
- which version of pyroSAR are you using?  
0.14
-  which function of pyroSAR did you call with which parameters?  
geocode(infile=scene, outdir=outdir, tr=10, t_srs=epsg, scaling='dB', removeS1BorderNoise=True, removeS1BorderNoiseMethod='pyroSAR', removeS1ThermalNoise=True, terrainFlattening=True, externalDEMFile=outdir + "/dem.tif", externalDEMApplyEGM=False, demResamplingMethod='BILINEAR_INTERPOLATION', imgResamplingMethod='BILINEAR_INTERPOLATION', speckleFilter=False, refarea=['sigma0','gamma0'], externalDEMNoDataValue=0, nodataValueAtSea=False, export_extra=['layoverShadowMask'], groupsize=gpt_workers, cleanup=True)
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
SNAP 8.0.4

The generated layover-shadow mask has 0 set as no-data value. Since 0 is also a valid value for data that is not layover/nor shadow, both valid data within scene coverage and "real" no-data outside of the scene coverage have the same value. It would be better if the no-data value is set to 255 (as proposed for the new NRB ARD product), to facilitate processing and to prevent confusion.

**Comment by johntruckenbrodt** [comment]
Hi @peterfriedl thanks for reporting this. I am afraid this is a problem with SNAP, which unfortunately does not make a differentiation between "0" and "no data" for any image. The only thing pyroSAR does is to assign 0 as no data value in the GeoTIFF metadata. I agree this is not a good idea. I will change it and will get in touch with the SNAP developers to see whether this can be changed.

**Comment by maawoo** [comment]
FYI, a related thread from the STEP forum: 
https://forum.step.esa.int/t/externaldemnodatavalue-can-greatly-change-performance/33504
