### ISSUE TITLE
Support for other DEMs in geocode function

### ISSUE THREAD

**Issue by DTMilodowski** [johntruckenbrodt/pyroSAR#177]
Hi John,

Hopefully a super quick request! In the geocode function, there is the demName argument to specify the auto-downloaded DEM. However, in the documentation only 'SRTM 1Sec HGT' is listed. Are there other options available currently supported by SNAP, such as the Copernicus glo30 DEM? Would it be possible to add this?

Sorry if I've missed something obvious.

Thanks, and best wishes!
David

**Comment by johntruckenbrodt** [comment]
Hi David,
All options supported by SNAP work, they are just not listed in the docs yet. Let's keep this open so I am reminded to do that.
Cheers
