### ISSUE TITLE
Suggestion for reordering of checks in function: get_egm_lookup

### ISSUE THREAD

**Issue by DTMilodowski** [johntruckenbrodt/pyroSAR#183]
This issue concerns the function get_egm_lookup https://github.com/johntruckenbrodt/pyroSAR/blob/2a1b352b205bb8bad641dd6e3b478d531696d8b4/pyroSAR/auxdata.py#L870

Specifically, in lines 918:927 the code checks
1) whether PROJ_DIR is writable
_then_
2) whether the gtx file is held locally.

If condition 1 fails, then an error message is returned, even if there is already a local copy in the required directory. If check 2 fails, then the gtx file is downloaded into PROJ_DIR. If the file is already available, then nothing is required.
This logic causes an issue with the permissions set up for our server system, where the standard PROJ_DIR location is read-only for most users.

Would it be possible for these checks to be switched, so that the check for writable access to PROJ_DIR is only done once it is established that a download is required? This would avoid errors being thrown by a lack of write-access to PROJ_DIR when write-access is not required as the file is already available in the local directory. As far as I can tell, it would just be a case of nesting the first test within the second.

Currently using pyrosar v0.15, installed via pip onto a linux CentOS operating system with python v3.9.

Thanks!

**Comment by johntruckenbrodt** [comment]
Makes perfect sense. Thanks a lot @DTMilodowski.
