### ISSUE TITLE
change a property in `/etc/snap.properties` via pyroSAR

### ISSUE THREAD

**Issue by jonathom** [johntruckenbrodt/pyroSAR#192]
Good afternoon all,
I'm wondering if I can use the functionality in [pyroSAR/examine.py](https://github.com/johntruckenbrodt/pyroSAR/blob/cc972d2edcdf4431cc5410ccca0529f0c80e095a/pyroSAR/examine.py) (or anywhere else for that matter) to set a property in the SNAP properties files (specifically `snap.userdir` in `/etc/snap.properties`) using pyroSAR. This is important because in my scenario I can't edit this file in another way (GUI, command line, etc.). My beginners-best-guess attempts have failed - I was looking in the direction of `__read_config` for checking and `__update_config_attr` for setting.. But even importing these functions fails for me. 
Here's how I imagined this to go:
```python
from pyroSAR.examine import ExamineSnap, __function_to_add_attribute
ExamineSnap().__function_to_add_attribute("snap.userdir", "/my/path")
```
leading to an updated `snap.properties` file with this line: `snap.userdir=/my/path`.

I am using pyroSAR inside a docker container inside spark, because I wanna parallelize S1 processing on a cluster. If you need more details let me know, but I believe a solution for this would be independent from where it is executed, i.e. work on my local installation as well.

**Comment by jonathom** [comment]
I realize now that the suggested file is probably only about the _pyroSAR configuration_, and not the SNAP configuration.. So, ignoring my misdirected attempt above my question still stands: Is it possible to set a SNAP parameter (e.g. in file `snap/etc/snap.properties`) via pyroSAR?

**Comment by jonathom** [comment]
`gpt_args` can be used for this, i.e. `gpt(..., gpt_args = ['snap.userdir=/my/path']`.

**Comment by johntruckenbrodt** [comment]
Hi @jonathom. At the moment pyroSAR is not making best use of these SNAP configuration files. True, this `Examine` functionality handles pyroSAR-specific configuration files and the ones from SNAP are mostly ignored. It would a larger effort to use and modify them. Good that you have discovered the `gpt_args` parameter.

**Comment by jonathom** [comment]
Thanks @johntruckenbrodt, I see now that it isn't necessary to change the config files when I can really pass all needed params via the call. Just needed to figure out _how_ ;) So, a note for future reference:
* [here](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/15269950/SNAP+Configuration)'s a list of SNAP parameters that can be set
* `gpt` tells you to append these parameters with `-D` of you want to set them so this is what you need to do for `gpt_args` as well: "`-D<name>=<value>   Defines a system property for this invocation.`" (from gpt command help)
* if you wanna set args that concers the java vm, i.e. parameters from gpt.properties, e.g. `-Xmx`, append `-J`, see [here](https://www.ej-technologies.com/resources/install4j/v/8.0/help/doc/concepts/vmParameters.html)
* all in all, this is the gpt call I ended up with: `gpt(<out_filename>, groups = groups, gpt_args = ['-Dsnap.userdir=.', '-J-Xmx4G'])`

**Comment by johntruckenbrodt** [comment]
awesome, thanks @jonathom
