### ISSUE TITLE
`snap.auxdata.dem_create` Check if files listed in VRT exist

### ISSUE THREAD

**Issue by maawoo** [johntruckenbrodt/pyroSAR#196]
Passing a VRT to `dem_create` that contains non-existing source files does not raise an error or at least warn the user of missing files. The resulting DEM is either just partly created or filled with nodata values if none of the source files are available. This could easily be overlooked by users and could result in incorrect results down the line if the output file is passed on to other software automatically.

**Comment by johntruckenbrodt** [comment]
Thanks @maawoo. Here some code that should be able to check it:
```python
from lxml import etree
from spatialist import Raster

def vrt_all_exist(fname):
    with Raster(fname) as ras:
        existing = ras.files
    existing.remove(fname)
    tree = etree.parse(fname)
    registered = tree.findall('.//SourceFilename')
    return len(existing) == len(registered)
```
I need to think a little about where to best integrate this.  
In the meantime, could you share the link to the GDAL issue you were mentioning in this context?
