### ISSUE TITLE
Cannot read version information from messages.log 

### ISSUE THREAD

**Issue by peterfriedl** [johntruckenbrodt/pyroSAR#201]
I am running pyroSAR 0.16 with the most up-to-date modules of SNAP:
[snap_installed_modules.txt](https://github.com/johntruckenbrodt/pyroSAR/files/8196414/snap_installed_modules.txt)
When starting SNAP, a messages.log file is being created in the folder exspected by 
 get_version() and it is read by get_version(). However, none of the expected patterns like e.g. org\.esa\.s1tbx\.s1tbx\.kit \[(?P<version>[0-9.]+) [0-9.]+ (?P<date>[0-9]{12}) is contained in the messages.log file: 
[messages.log](https://github.com/johntruckenbrodt/pyroSAR/files/8196437/messages.log)
This consequently leads to the error message "RuntimeError: cannot read version information from <path_to_file>Please restart SNAP."
Does get_version() need to be adapted or does a malfunction of SNAP produce a wrong messages.log file here? Any suggestions? 

Thanks for your help!
Peter

**Comment by johntruckenbrodt** [comment]
Hi Peter. This file is created/updated with the needed info when
- starting the SNAP GUI
- [updating SNAP over the command line](https://senbox.atlassian.net/wiki/spaces/SNAP/pages/30539785/Update+SNAP+from+the+command+line)

Cheers

**Comment by peterfriedl** [comment]
It was a problem on my side. Apparently, if a X11 window server is not available, SNAP GUI cannot be started correctly and hence the version infos are not written to the messages.log file, becauses SNAP stops beforehand.
