### ISSUE TITLE
Inconsistent Group Error [SNAP]

### ISSUE THREAD

**Issue by James-Ash20** [johntruckenbrodt/pyroSAR#206]
Snap version = 8.0.6
python conda install pyroSAR = 0.16.3 
S1B_IW_GRDH_1SDV_20170701T015715_20170701T015744_006288_00B0E0_043F.zip

With IPF<2.9, "pyroSAR" border noise removal method and Remove GRD Border Noise in the groups, an inconsistent group error is raised. 

groups = [['Read', 'Remove-GRD-Border-Noise'], ['Calibration', 'ThermalNoiseRemoval'], ['Apply-Orbit-File'], ['Terrain-Flattening'], ['Speckle-Filter'], ['Terrain-Correction', 'Write']]

Removing 'Remove-GRD-Border-Noise' leaves the following:
 [['Read'], ['Calibration', 'ThermalNoiseRemoval'], ['Apply-Orbit-File'], ['Terrain-Flattening'], ['Speckle-Filter'], ['Terrain-Correction', 'Write']]

Prior to version 0.15, 'Remove-GRD-Border-Noise' was not in the front of the groups and thus not an issue. 'Read' needs to be moved in front of Calibration.
 [['Read', 'Calibration', 'ThermalNoiseRemoval'], ['Apply-Orbit-File'], ['Terrain-Flattening'], ['Speckle-Filter'], ['Terrain-Correction', 'Write']]

The file this code exists in is pyroSAR/snap/auxil.py. Edits likely need to be made to the function gpt()

**Comment by johntruckenbrodt** [comment]
Thanks a lot for the bug report and your email @James-Ash20. I am currently traveling and have not found the time to look into this. Sorry for the late reply. I will get into this in the next days.
