### ISSUE TITLE
UserWarning: could not find Gamma installation directory; please set the GAMMA_HOME environment variable   

### ISSUE THREAD

**Issue by GISer-longchaohuo** [johntruckenbrodt/pyroSAR#240]
UserWarning: could not find Gamma installation directory; please set the GAMMA_HOME environment variable
warnings.warn('could not
![image](https://user-images.githubusercontent.com/60539729/216335835-3ee60f55-5bae-4302-bcdd-11dbfc58fc36.png)
![222222222](https://user-images.githubusercontent.com/60539729/216336072-fa99cf85-0391-4a54-9f6b-dee893a81609.png)
 find Gamma installation directory; please set the GAMMA_HOME environment variable'

**Comment by johntruckenbrodt** [comment]
Hi @GISer-longchaohuo. If you wnat to process with GAMMA you need to point pyroSAR to the installation directory. Di you have a GAMMA installation? If not you can only use SNAP.

**Comment by johntruckenbrodt** [comment]
closing this as there hasn't been an update in over three months. Feel free to reopen.

**Comment by GISer-longchaohuo** [comment]
oh. Thanks for the reply, I'll try again.
