### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by jie666-6** [johntruckenbrodt/pyroSAR#241]
- which operating system are you using?  
 Windows 10, python = 3.6

- which environment is pyroSAR running in?  
Anaconda environment/virtual environment

I am trying to install pyrosar using 'conda install --channel conda-forge pyrosar' but it is stuck in the solving environment step (more than 12 hours) and it seems that it will never finish. I also try to use anaconda navigator to install this package, but the problem is still there the 'solving package specifications' will never finish.

I would like to ask how should I solve this issue or is there any other way that I can install pyrosar?

Thanks in advance

**Comment by johntruckenbrodt** [comment]
Hi @jie666-6. Yes, this can happen sometimes. You can try two things.
- installation with [mamba](https://mamba.readthedocs.io/en/latest/index.html). This is usually faster and might be able to resolve the dependencies
- set up an environment with a more recent Python version.

If possible, I would go for the latter.  After all, Python 3.6 is quite old and might not be fully supported any longer.

**Comment by jie666-6** [comment]
Thanks a lot! Once I changed to python 3.9, the installation went well.

**Comment by johntruckenbrodt** [comment]
Great! Happy processing.
