### ISSUE TITLE
Correct Documentation: use of gpt()

### ISSUE THREAD

**Issue by jonathom** [johntruckenbrodt/pyroSAR#249]
In the [example for the use of gpt()](https://github.com/johntruckenbrodt/pyroSAR/blob/853eca4b0940b3270b3848757269f3eca07ef321/docs/source/general/snap.rst#L56) I noticed that an argument is missing: `tmpdir` seems to have become a required argument by now. I'm opening this issue here because I don't know in what form that fact should be worked into the example. I would suggest this:
```python
from pyroSAR.snap.auxil import gpt
import tempfile

gpt('outname_proc.xml', tmpdir=tempfile.gettempdir())
```

**Comment by johntruckenbrodt** [comment]
You found another one 😅, thanks a lot @jonathom. Principally your idea is a good one, but I do not want to promote to directly write to the system's temporary directory. Multiple `gpt` calls could write to it and this would clash with the `cleanup` mechanism. So in the PR I have gone the easy route to just declare ``tmpdir='.'``. Is it clearer now?

**Comment by jonathom** [comment]
Yes, makes more sense. Perfect!
