### ISSUE TITLE
Travis CI testing with Python 3.5+

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#25]
The current Travis OS is Ubuntu Trusty, which comes with Python 3.4. Testing with Python 3.5 or 3.6 is not possible because system site packages need to be enabled and this seems to only work with the OS-installed Python version. Is there a way to still test the other versions?

**Comment by ibaris** [comment]
Do you have already tried something like this at the travis configuration file?
```python
python:
- "3.5_with_system_site_packages"```

**Comment by felixcremer** [comment]
We can try to use pygdal to install the python gdal bindings.
I can get the python2.7 test going with these changes to the .travis.yml:
python:
 - "2.7"
 - "3.4"
 - "3.5"

virtualenv:
before_script:

install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install coverage
  - pip install "pygdal>=2.1.3,<=2.1.3.999"
  - python setup.py install
  
before_install:
  - sudo add-apt-repository ppa:ubuntugis/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install gdal-bin python-gdal python3-gdal libproj-dev libgdal1-dev -y
  - pip install -U pip

Unfortunately, in python 3 I get an import error. The importing of ogr fails.

**Comment by ibaris** [comment]
> Unfortunately, in python 3 I get an import error. The importing of ogr fails.
This is exactly the same error that I got. And I tried with all of my packages and the result is always the same.

**Comment by Echelon9** [comment]
After some dependency wrangling, I've got a WIP patch that works testing Python 3.4 - 3.7 on Travis-CI.
See: https://travis-ci.org/Echelon9/pyroSAR/builds/455867555

Changes required before the patch could be properly upstreamed:
* Clean up the documentation.
* Confirm this doesn't regress Windows CI on appveyor.
* Resolve the Python 2.7 only problem with sqlite dependencies [appears unrelated to this patch].

For discussion:
* *Preferred GDAL Python binding*: Unofficial `pygdal` has some [real](https://github.com/nextgis/pygdal/issues/31) [problems](https://github.com/nextgis/pygdal/issues/30), I would instead strongly recommend using the official `gdal` Python package to provide the bindings to the local libgdal-dev.

The benefits of using the official `gdal` Python package bindings are full support for Python 3, lockstep version releases alongside libgdal-dev, and with some clever scripting (see .travis.yml in the patch) it can be automated as part of the instructions to setup a development environment.

**Comment by johntruckenbrodt** [comment]
As of March 29, testing is now done with Python 3.5 in Ubuntu Xenial. This is currently the latest setup to support using system site packages
