### ISSUE TITLE
Replacing SciHub URLs?

### ISSUE THREAD

**Issue by timatcambrio** [johntruckenbrodt/pyroSAR#266]
Are there plans to replace `url_option` 1 under `OSV.catch()` with a corresponding query/download URL under the new Copernicus Data Space ecosystem?

**Comment by johntruckenbrodt** [comment]
@timatcambrio there were no plans so far. But since the Copernicus Open Access Hub is going to shut down end of this month, it is acutally quite urgent to switch to CDSE. Thanks for opening the issue.

**Comment by christianlloyd** [comment]
Is there any update on this as ESA have now shutdown Scihub?

**Comment by johntruckenbrodt** [comment]
For now I am changing the default option for OSV download and remove the Scihub option. CDSE download can follow later. It might be tricky to implement because it requires authentication for everything.

**Comment by johntruckenbrodt** [comment]
Dedicated issue for CDSE download: https://github.com/johntruckenbrodt/pyroSAR/issues/276
