### ISSUE TITLE
Unit tests and .travis.yml

### ISSUE THREAD

**Issue by ibaris** [johntruckenbrodt/pyroSAR#27]
I wrote some unit tests to test the classes ExamineExe and ExamineSnap. After that I would like to change the .travis.yml file and download snap from "http://step.esa.int/downloads/6.0/installers/esa-snap_sentinel_unix_6_0.sh" to install it within travis. Thus, I add the following code block to the `before_install` section:
```python
  - sudo apt-get install wget
  - wget -O esa-snap_sentinel_unix_6_0.sh http://step.esa.int/downloads/6.0/installers/esa-snap_sentinel_unix_6_0.sh
  - sudo chmod +x esa-snap_sentinel_unix_6_0.sh
  - sudo ./esa-snap_sentinel_unix_6_0.sh
```
The problem is now travis uses the config file from the original repository and not from the forked one.  Do you guys have any suggestions how we could solve this?

**Comment by felixcremer** [comment]
The easiest way is to allow travis to test on your own fork.
Therefore go to travis-ci.org and switch it on. 
Then you could also use the trigger build function to test your .travis.yml without bloating your git history. 
https://blog.travis-ci.com/2017-08-24-trigger-custom-build

**Comment by ibaris** [comment]
Now it works. Thank you! 

Now I have to solve the issue that travis can not install the snap.sh file without a user confirmation:
```
$ ./esa-snap_sentinel_unix_6_0.sh
Unpacking JRE ...
Preparing JRE ...
Starting Installer ...
puter.
OK [o, Enter], Cancel [c]
´´´

I hope I can solve this issue today.

**Comment by felixcremer** [comment]
> Now I have to solve the issue that travis can not install the snap.sh file without a user confirmation: 

Try using the quiet option -q for the install.

**Comment by ibaris** [comment]
I solved it with `yes "" | ./esa-snap_sentinel_unix_6_0.sh` and the installation works. But the class `ExamineSnap` can not still find the snap installation on Travis. I will keep trying.

Thank you for your help 👍
