### ISSUE TITLE
Issue with RuntimeError: data format not supported

### ISSUE THREAD

**Issue by 1milenac** [johntruckenbrodt/pyroSAR#278]
Hello! Im trying to perform identify on two zips. They are from the same source, only difference is a date of acquisition. One zip is working perfently but the other is not for some reason. I have investigated the content and look same, The zip is not broken

`>>> identify(r'C:\Users\48535\Desktop\s1\zips\S1A_IW_GRDH_1SDV_20231124T042812_20231124T042837_051354_06325B_BA6D.SAFE.zip')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\48535\anaconda3\envs\pygdal\Lib\site-packages\pyroSAR\drivers.py", line 125, in identify
    raise RuntimeError('data format not supported')
RuntimeError: data format not supported
>>>
KeyboardInterrupt
>>>  identify(r'C:\Users\48535\Desktop\s1\zips\2023-11-03\S1A_IW_GRDH_1SDV_20231103T045136_20231103T045201_051048_0627BA_4146.SAFE.zip')
  File "<stdin>", line 1
    identify(r'C:\Users\48535\Desktop\s1\zips\2023-11-03\S1A_IW_GRDH_1SDV_20231103T045136_20231103T045201_051048_0627BA_4146.SAFE.zip')
IndentationError: unexpected indent
>>> identify(r'C:\Users\48535\Desktop\s1\zips\2023-11-03\S1A_IW_GRDH_1SDV_20231103T045136_20231103T045201_051048_0627BA_4146.SAFE.zip')
<pyroSAR.drivers.SAFE object at 0x00000243531DFAA0>   `

What can be a reason?

PS This case is different that my previous issue because here I'm trying on windows this time with pyroSAR Version: 0.22.1.

**Comment by johntruckenbrodt** [comment]
Hi @1milenac I assume you have obtained the data from CDSE. In this case this should be the same as reported in https://github.com/johntruckenbrodt/pyroSAR/issues/269. Updating to the latest version 0.23.0 should fix it. Closing this for now, feel free to reopen if necessary.

**Comment by 1milenac** [comment]
Yes, thanks. Updating the library solved the problem!
