### ISSUE TITLE
Issue with GeoCode in last version of pyroSAR

### ISSUE THREAD

**Issue by FranckNIRD** [johntruckenbrodt/pyroSAR#283]
- which operating system are you using?  
Ubuntu 22.04
- which environment is pyroSAR running in?  
Python installation 3.10.12 under Conda Environnement
- which version of pyroSAR are you using?  
one install via pip
-  which function of pyroSAR did you call with which parameters?  
Geocode
- if applicable, which version of SNAP or GAMMA are you using in pyroSAR?
SNAP 5.0
- the full error message

Exception has occurred: AttributeError
'ExamineSnap' object has no attribute 'gpt'
  File "/home/nivole/Documents/18_detection_TFAC_MERCORAIL/MultiTFAC.py", line 45, in <module>
    geocode(
AttributeError: 'ExamineSnap' object has no attribute 'gpt'

in the previous version, this code woked :

geocode( infile="/home/Documents/18_detection_TFAC/FichierS1/S1_NOUMEA/S1B_IW_GRDH_1SDV_20200117T182230_20200117T182247_019860_0258F5_0531.zip",
    outdir="./Geocode/Noumea",
    tr=20,
    scaling="dB",
    t_srs=4326,
    refarea="sigma0",
    terrainFlattening=False,
    speckleFilter = 'Median',
)

I changed bashrc to get the good path.

**Comment by johntruckenbrodt** [comment]
@FranckNIRD any update on this?

**Comment by FranckNIRD** [comment]
I didn't have more time to work on. I Keep in mind your answer. I will have to work again with Sentinel1. For the moment I close issues. Thank you for your help.

**Comment by johntruckenbrodt** [comment]
Thanks for the update @FranckNIRD. Reach out any time if you get back into SAR processing.
