### ISSUE TITLE
Problem with orbit files

### ISSUE THREAD

**Issue by 1milenac** [johntruckenbrodt/pyroSAR#285]
- which operating system are you using?  
Linux ac0736 4.18.0-477.27.1.el8_8.x86_64
- which environment is pyroSAR running in?  
virtual environment
- which version of pyroSAR are you using?  
I'm using the latest version 0.23.0, installed with python -m pip install pyroSAR
-  which function of pyroSAR did you call with which parameters?  
- I'm running: geocode(
            infile=str(self.input_image),
            outdir=str(self.output_vh_image),
            spacing=10,
            refarea=["sigma0"],
            demName="SRTM 3Sec",
            polarizations="VH",
            scaling="linear",
            speckleFilter="Lee Sigma",
            demResamplingMethod="BILINEAR_INTERPOLATION",
            imgResamplingMethod="BILINEAR_INTERPOLATION",
            nodataValueAtSea=True,
            allow_RES_OSV=True,
            removeS1ThermalNoise=False,
            removeS1BorderNoise=False,
            terrainFlattening=False,
        )

- the full error message
Error: [NodeId: Apply-Orbit-File] No valid orbit file found for 01-FEB-2022 16:35:35.154410
Orbit files may be downloaded from https://scihub.copernicus.eu/gnss/odata/v1/
and placed in /net/XX/XX/XX/.snap/auxdata/Orbits/Sentinel-1/POEORB/S1A/2022/02

[S1A_IW_GRDH_1SDV_20220201T163644_20220201T163709_041722_04F6E6_61EB.SAFE_tmp1.xml] failed with return code 1`

**Comment by johntruckenbrodt** [comment]
Thanks @1milenac for reporting the bug. A fix is on the way.

**Comment by 1milenac** [comment]
H @johntruckenbrodt ! i am sorry I need to reopen. Because apparently running geocode on the s1 images 2024 returns now an error: requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://step.esa.int/auxdata/orbits/Sentinel-1/RESORB/S1A/2024/01/. How this can be fixed? 

This is example zip scene: S1A_IW_GRDH_1SDV_20240103T164343_20240103T164408_051945_0646C5_4294.SAFE.zip

**Comment by johntruckenbrodt** [comment]
Hi @1milenac the fix has not been released in a new version yet. I will do that tomorrow. Sorry for the delay.

**Comment by 1milenac** [comment]
Thank you!

**Comment by johntruckenbrodt** [comment]
The new version 0.24.0 is out now. Thanks for discovering this bug.
