### ISSUE TITLE
Setup Sphinx to make documentation on readthedocs

### ISSUE THREAD

**Issue by felixcremer** [johntruckenbrodt/pyroSAR#29]
There are a lot of docstrings hidden in the code. 
To make them easy accessible it would be good to have them displayed on 
readthedocs.io toghether with short introductions in the functionality of pyroSAR.

Therefore, we have to setup sphinx to automatically get the docstrings in a nice format.

**Comment by ibaris** [comment]
I have some experience in that point (Sphinx and RTD). Sphinx is in some cases very difficult to manage due to the packages to mock in the config.py. I can help you with that if you want.
