### ISSUE TITLE
Error importing geocode when using pyroSAR 0.26 installed from  pip

### ISSUE THREAD

**Issue by vchaparro** [johntruckenbrodt/pyroSAR#311]
Hi @johntruckenbrodt,

 I'm experienced a problem, regarding the installation we have just talked about in issue #304. When I install the last version from git:

`RUN apt-get update && \
    apt-get install git -y && \ 
    pip install git+https://github.com/johntruckenbrodt/pyroSAR.git && \`
    
Pyrosar works properly with snap 10. However, if I install pyroSAR directly from pip (`pip install pyroSAR`), I get the last version according to my pip list, but I get this error:

_/preprocess.py", line 4, in <module>
    from pyroSAR.snap import geocode
  File "/usr/local/lib/python3.10/site-packages/pyroSAR/__init__.py", line 1, in <module>
    from .drivers import *
  File "/usr/local/lib/python3.10/site-packages/pyroSAR/drivers.py", line 51, in <module>
    from . import S1, patterns
  File "/usr/local/lib/python3.10/site-packages/pyroSAR/S1/__init__.py", line 3, in <module>
    from .auxil import OSV, removeGRDBorderNoise
  File "/usr/local/lib/python3.10/site-packages/pyroSAR/S1/auxil.py", line 29, in <module>
    from . import linesimplify as ls
  File "/usr/local/lib/python3.10/site-packages/pyroSAR/S1/linesimplify.py", line 17, in <module>
    from spatialist.ancillary import rescale
  File "/usr/local/lib/python3.10/site-packages/spatialist/__init__.py", line 4, in <module>
    from . import raster
  File "/usr/local/lib/python3.10/site-packages/spatialist/raster.py", line 23, in <module>
    from osgeo import gdal, gdal_array, osr
  File "/usr/local/lib/python3.10/site-packages/osgeo/gdal_array.py", line 13, in <module>
    from . import _gdal_array
ImportError: cannot import name '_gdal_array' from 'osgeo' (/usr/local/lib/python3.10/site-packages/osgeo/__init__.py)_

_Originally posted by @vchaparro in https://github.com/johntruckenbrodt/pyroSAR/issues/304#issuecomment-2114627690_

**Comment by johntruckenbrodt** [comment]
GDAL is a tricky one to handle with the pip installation. One can install the gdal pip package but it won't work out pf the box because the C/C++ library is not installed automatically. This is why using conda/mamba is a lot easier.  

You can pip-install GDAL like this:
```shell
apt install gdal
pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="$(gdal-config --cflags)"
```
This way you ensure that the right Python binding is installed for the version you have installed with apt.

I can't exactly tell why you cannot import `gdal_array`, but I suspect that either the apt and pip versions don't match or there is no apt installation.

**Comment by vchaparro** [comment]
Thanks @johntruckenbrodt ,
My installation was almost the same:
`pip install GDAL==$(gdal-config --version) --global-option=build_ext --global-option="-I/usr/include/gdal"`

Changing to --global-option="$(gdal-config --cflags)" made the difference, and now it works :)

**Comment by johntruckenbrodt** [comment]
Great :smiley:
