### ISSUE TITLE
Proposal: Append GeoTIFF file extension to file name after geocode function (SNAP)

### ISSUE THREAD

**Issue by jonas-eberle** [johntruckenbrodt/pyroSAR#33]
I use the geocode function from pyroSAR.snap. When processing the data the resulting files are in GeoTIFF format, but unfortunately they have no file extension: 
S1A__IW___D_20170130T042224_VH_bnr_orb_cal_tf_tc_dB        S1B__IW___D_20170129T042958_VH_bnr_orb_cal_tf_tc_dB
S1A__IW___D_20170130T042224_VV_bnr_orb_cal_tf_tc_dB        S1B__IW___D_20170129T042958_VV_bnr_orb_cal_tf_tc_dB

`gdalinfo S1B__IW___D_20171130T061758_VH_bnr_orb_cal_tf_tc_dB`
`Driver: GTiff/GeoTIFF`

I would propose to automatically add the file ending for GeoTIFF files, so it is easier for users to open such outupt files in GIS Desktop software. Otherwise users need to rename the files on their own.

**Comment by johntruckenbrodt** [comment]
Strange. This behavior comes from GDAL itself. In my version the extension is set automatically by GDAl if the respective driver is selected.
