### ISSUE TITLE
Errors in ExamineSnap

### ISSUE THREAD

**Issue by jonas-eberle** [johntruckenbrodt/pyroSAR#34]
The last commit has introduced some errors (Linux environment) when calling pyroSAR.snap.geocode: 
```
Traceback (most recent call last):
  File "/usr/local/bin/geocode.py", line 13, in <module>
    from pyroSAR.snap import geocode
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/__init__.py", line 4, in <module>
    snap_config = ExamineSnap()
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 250, in __init__
    self.__get_etc()
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 262, in __get_etc
    except WindowsError:
NameError: global name 'WindowsError' is not defined
```

If I adjust this manually to OSError than the following error occurs: 
```
Traceback (most recent call last):
  File "/usr/local/bin/geocode.py", line 13, in <module>
    from pyroSAR.snap import geocode
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/__init__.py", line 4, in <module>
    snap_config = ExamineSnap()
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 250, in __init__
    self.__get_etc()
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 260, in __get_etc
    self.config_path = os.path.join(self.etc, [s for s in self.auxdata if "snap.auxdata.properties" in s][0])
IndexError: list index out of range
```

I also do not understand why the "etc" directory is related to the path of the executable (self.path), see line 258 of pyroSAR/snap/auxil.py: 
`self.etc = os.path.join(os.path.dirname(os.path.dirname(self.path)), 'etc')`

On my system I have an "etc" directory within HOME/.snap with configuration files.

**Comment by ibaris** [comment]
The exception with `WindowsError` was my foult. I change that imminently. 
The main idea with the `etc` directory was that we can read all the configuration parameter and the URL for the DEMs from the configuration file. Any how, the 'IndexError' is a little bit strange. Can you post the content of your `etc` directory? Which version of snap do you use? It could also be possible that something changed from version 5 to 6.

**Comment by jonas-eberle** [comment]
In this case I use SNAP 5. The path variable is set to /usr/local/bin/snap, which is a link: 
`lrwxrwxrwx 1 root staff 18 Mar 31 14:13 /usr/local/bin/snap -> /opt/snap/bin/snap`

The etc variable (https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/snap/auxil.py#L258) is then /usr/local/etc but it should be /opt/snap/etc. So it seems that the link generates the error.

**Comment by ibaris** [comment]
Thank you very much for the hint. I add these lines and pushed it to my forked repository to check if the path is a link:
```python
if os.path.islink(self.path):
      self.path = os.path.realpath(self.path)
```

Could you please try this with your system and tell me the result? The problem is that I am not familiar with Linux systems.  I testet this on our server and it worked. Moreover, the tests also passed on TRAVIS CI.

**Comment by jonas-eberle** [comment]
Good. This works, but there is another error: 
```
Traceback (most recent call last):
  File "usr/local/bin/geocode.py", line 25, in <module>
    geocode(infile=args.infile, outdir=args.outdir, shapefile=args.shapefile, tr=args.resolution, scaling='dB')
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/util.py", line 182, in geocode
    suffix = parse_suffix(workflow)
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 47, in parse_suffix
    suffix = '_'.join(filter(None, [LOOKUP.snap.suffix[x] for x in [y.attrib['id'] for y in nodes]]))
TypeError: tuple indices must be integers, not str
```

LOOKUP.snap.suffix is a dictionary within a tuple. I guess this is a mistake. There is an extra comma at the end of the dictionary that changes the variable to tuple: https://github.com/ibaris/pyroSAR/blob/master/pyroSAR/_dev_config.py#L87
```
snap_suffix = {'Apply-Orbit-File': 'Orb',
               'Calibration': 'Cal',
               'Cross-Correlation': '',
               'LinearToFromdB': 'dB',
               'Remove-GRD-Border-Noise': 'bnr',
               'SAR-Simulation': 'Sim',
               'SARSim-Terrain-Correction': 'TC',
               'Subset': '',
               'Terrain-Correction': 'TC',
               'Terrain-Flattening': 'TF',
               'Read': '',
               'Write': ''},
```

**Comment by ibaris** [comment]
Roger that! I delete the comma. Exactly as you said the comma convert the `dict` into a `tuple`. I will push the changes in to my forked repository and delete this issue here. If you find any other Bugs we can generate a new issue. 

Thanks again for your message, advices and suggestions.
