### ISSUE TITLE
Set __version__ at a single source

### ISSUE THREAD

**Issue by felixcremer** [johntruckenbrodt/pyroSAR#39]
It would be good to have the possibility to get the installed version of pyroSAR with:
pyroSAR.__version__
This should be defined at one place in the source code and used by setup.py.
Relevant links I found for this are:

https://pypi.python.org/pypi/setuptools_scm
https://packaging.python.org/guides/single-sourcing-package-version/

**Comment by johntruckenbrodt** [comment]
okay for starters I have tagged a version 0.3
