### ISSUE TITLE
pygdal possible as alternative for the GDAL package?

### ISSUE THREAD

**Issue by ikselven** [johntruckenbrodt/pyroSAR#4]
From `pygdal` package description:

> Virtualenv and setuptools friendly version of standard GDAL python bindings

Switching from package `GDAL` to `pygdal` might make installing the dependencies easier, with less manual intervention.

**Comment by ibaris** [comment]
I do not know whether it is important or not but pygdal only supports a small set of GDAL versions.

**Comment by johntruckenbrodt** [comment]
Haven't had a look in it yet. It would of course be good to have the full set of GDAL functionality available even if it not used (yet). The fewer dependencies the better I would say. @ibaris whilst you're elooking into rasterio, please give this package a look too.

**Comment by felixcremer** [comment]
pygdal is only a virtualenv friendly version of the standard gdal python bindings. It eases the installation process and is  not an alternative to rasterio. This changes the installation of gdal for the user but not our usage in the package.
