### ISSUE TITLE
Configuration Management System

### ISSUE THREAD

**Issue by ibaris** [johntruckenbrodt/pyroSAR#45]
The problem is we must deal with paths, like the path of snap, the path of etc directory or the paths of different DEMs and orbit files. The main idea was to focus all these information in one configuration file. But I think we have to discuss the best and suitable way to do it. The questions are:
- How should the file look like?
- Which header information we should use?
- Which file extension is the best (.txt, .CSV etc.)?
- Should we code a own class or a module?

**Comment by johntruckenbrodt** [comment]
Yep, it's about time we discuss this. Here'a first link:
https://hackernoon.com/4-ways-to-manage-the-configuration-in-python-4623049e841b
JSON looks quite intuitive. How about something like this:
```Python
import os
import json


class Config(object):
    def __init__(self, configfile):
        self.config = configfile

    def __getattr__(self, item):
        if item == 'config':
            return self.config
        else:
            if os.path.isfile(self.config):
                with open(self.config, 'r') as f:
                    conf = json.load(f)
                return conf[item]
            else:
                raise AttributeError("no attribute '{}'".format(item))

    def __setattr__(self, key, value):
        if key != 'config':
            if os.path.isfile(self.config):
                with open(self.config, 'r') as f:
                    conf = json.load(f)
            else:
                conf = dict()
            conf[key] = value
            with open(self.config, 'w') as f:
                json.dump(conf, f)
        super(Config, self).__setattr__(key, value)


filename = 'E:/DATA/test/json/test.json'
conf = Config(filename)
conf.dempath = '/path'
print(conf.config)
print(conf.dempath)
```
This basically overrides the getter and setter method to read the attribute directly from the file and rewrite this file once an attribute is (re)set. One could even go further and allow only certain keys to be set.

**Comment by ibaris** [comment]
@johntruckenbrodt That looks awesome. I go a little bit deeper in JSON because I know this only to specify geometric objects like area of interest or something like this.

**Comment by jonas-eberle** [comment]
For configuration, I mostly like to use ini files that can be read by the configparser library included in Python: 
https://gist.github.com/mingrammer/baa0242241ad86bf2ac174bc8b313ea6#file-using-external-file-config-ini-ini
https://gist.github.com/mingrammer/fe4440b750184ff658790ce0cb4d474c#file-using-external-file-py

It is very easy to edit (from my point of view also easier than working with JSON files). But of course JSON is also fine.

**Comment by johntruckenbrodt** [comment]
Thanks for the suggestion @jonas-eberle! We'll look into it.

**Comment by johntruckenbrodt** [comment]
Wrapping up from today's meeting..let's create an ini configuration file containing, for starters, the SNAP executable, GPT executable and ETC directory path. If SNAP is not installed, and thus the executables not found by pyroSAR, these entries are written as empty strings to the configuration. This file needs to be read on module import and, if an executable name is empty, another check needs to be performed to find the executables to find out whether SNAP has been installed in the meantime.
@ibaris please integrate this basic config in pull request #44 and close the issue once everything works.

**Comment by johntruckenbrodt** [comment]
This has now been realized with the general class `_dev_config.ConfigHandler` and classes `gamma.auxil.ExamineGamma` and `snap.auxil.ExamineSnap` for module-specific configuration.
