### ISSUE TITLE
Execution of geocode raises an error

### ISSUE THREAD

**Issue by JohannesBalling** [johntruckenbrodt/pyroSAR#46]
Dear reader,

I installed PyroSAR, the needed extensions (SQLite + SpatiaLite) and SNAP as described here on Github on a Ubuntu server. Afterwards I was following the instruction of the example and everything works fine. BUT when I try to pre-process one Sentinel-1 image via pyroSAR, the geocode function results in an error.

The script I am using follows the instructions also given by the Readme on the front-page:
# Script 
```
from pyroSAR import identify
from pyroSAR.snap import geocode

name = 'path/S1A_IW_SLC__1SDV_20180605T111503_20180605T111531_022220_026773_82A0.zip'
scene = identify(name)
resolution = 20
outdir = 'path'

geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db')
```

# Result
In the outdir a .xml-file was created, but nothing else. 
# Error
```
Traceback (most recent call last):
  File "pre_processing_test.py", line 17, in <module>
    geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db')
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/util.py", line 266, in geocode
    gpt(outname + '_proc.xml')
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 214, in gpt
    proc = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

```
# Question
The Question I have is, whether I am missing something I should have done during the installation or what the origin of that error is in general. Thank you very much in advance and if you need any additional information, please let me know.

Greetings,
Johannes

**Comment by ibaris** [comment]
Thank you very much for the report Johannes :blush:.

**Comment by JohannesBalling** [comment]
Yes, both are correct. Out of convenient I left them out of the script.

PyroSAR is able to identify the sentinel-1 image in the inpath and also writes a xml-file in the outpath.

Thank you for your help already

**Comment by johntruckenbrodt** [comment]
Hi @JohannesBalling, thanks for pointing out this issue. The pyroSAR function gpt, which is called by geocode internally to process your workflow, could not find SNAP's gpt command line executable. I will upload a fix in a minute.

**Comment by JohannesBalling** [comment]
@johntruckenbrodt thank you very much for the fast reply and your help!

**Comment by johntruckenbrodt** [comment]
no worries. I hope it works for you now.

**Comment by JohannesBalling** [comment]
After upgrading pyrosar I still get the following error:

```
Traceback (most recent call last):
  File "test_pre_processing_v_02.py", line 12, in <module>
    geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db')
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/util.py", line 266, in geocode
    gpt(outname + '_proc.xml')
  File "/usr/local/lib/python2.7/dist-packages/pyroSAR/snap/auxil.py", line 219, in gpt
    proc = sp.Popen(cmd, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I checked again and snap is installed properly under : /usr/local/snap

**Comment by johntruckenbrodt** [comment]
Nice one! Fingers crossed..

**Comment by JohannesBalling** [comment]
@johntruckenbrodt sorry to bother you again, but this time I get another error message:

`('failed: ', 'S1A_IW_SLC__1SDV_20180606T224109_20180606T224136_022242_02681D_C534.zip')`

**Comment by johntruckenbrodt** [comment]
Now you got us. Function `geocode` currently does not support Sentinel-1 SLC data. Sorry I din't see that in your issue description. I must admit, that's not clear at all from the function name. For now, I will just add an extra check into the function and give a meaningful error message in case S1 SLC data is defined. I actually have this on my list for quite some time already and will try to work on this in the next days. It shouldn't bee too hard to integrate the S1 deburst step into the workflow. I'll give you a notice once I have integrated this.

**Comment by JohannesBalling** [comment]
Ahhh ok, that makes sense then. I will download some GRD data to see whether it works then. Thank you for your affords and let me know when you found some time to integrate the S1 deburst step in the workflow. Thank you also for that very much in advance.

**Comment by johntruckenbrodt** [comment]
Sure thing. Thank you for helping improve the software. We'll stay in touch

**Comment by JohannesBalling** [comment]
Hey, I would like to say that it works now with GRD files, but it does not. I still get this error message:

`('failed: ', 'S1A_IW_GRDH_1SDV_20180623T224837_20180623T224902_022490_026F95_AFAC.zip')`

# Script
Just to check again following is the script I am using
```from pyroSAR import identify
from pyroSAR.snap import geocode

# parameters
name = '/media/DATA4/balli001/Data/01_Sumatra/01_Sentinel_1/01_raw/S1A_IW_GRDH_1SDV_20180623T224837_20180623T224902_022490_026F95_AFAC.zip'
scene = identify(name)
resolution = 20
outdir = '/media/DATA4/balli001/Data/01_Sumatra/01_Sentinel_1/02_pre_processed/'


geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db')
```

**Comment by johntruckenbrodt** [comment]
Sumatra huh :-D? I'm just donwloading the scene and will have a look

**Comment by JohannesBalling** [comment]
Yeah, Indonesia this time :) let me know whether it works for you. Because I seriously dont know what the problem is.

**Comment by johntruckenbrodt** [comment]
Ok so I was able to process the scene. There must be something going on with SNAP. We already have on our agenda to fetch all those warnings and errors raised by gpt within python. For now let's start gpt outside of pyroSAR to see what's going on. Could you please run geocode in test mode to just write the workflow without executing it:
```Python
geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db', test=True)
``` 
and then call gpt on it directly via command line:
```Shell
/usr/local/snap/bin/gpt S1A__IW___D_20180623T224837_bnr_Orb_Cal_TF_TC_dB_proc.xml
```
What errors do you get?

**Comment by JohannesBalling** [comment]
Hey John,

so I just run the script in test mode and an xml file was created. When I want to preprocess the image via the xml file directly in command line, i get the following error:

```
WARNING: org.esa.snap.core.util.ServiceFinder: Can't search for SPIs, not a directory: /home/balli001/.snap/snap-python
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Loading external tools...
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /usr/local/snap/s2tbx
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Scanning for external tools adapters: /usr/local/snap/java
SEVERE: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Failed scan for Tools descriptors: I/O problem: /usr/local/snap/java
java.lang.NullPointerException

Error: [NodeId: Remove-GRD-Border-Noise] java.lang.NullPointerException
```

I also applied pyroSAR respectively the geocode function on an older image from 2015. This worked totally fine and i got pre-processed Sentinel-1 images.

**Comment by johntruckenbrodt** [comment]
Mh this is very likely related to your SNAP version. The border noise removal is not necessary anymore since IPF version 2.9, which was introduced on Jan 26th 2018. See this document [here](https://sentinel.esa.int/documents/247904/2142675/Sentinel-1-masking-no-value-pixels-grd-products-note). An older SNAP version likely does not automatically skip this removal step if the IPF version in the product is >=2.9. You can generally check it like this:
```Python
from pyroSAR import identify
id=identify('S1A_IW_GRDH_1SDV_20180623T224837_20180623T224902_022490_026F95_AFAC.zip')
print(id.meta['IPF_version'])
```

**Comment by JohannesBalling** [comment]
Thank you very much. Unfortunately, I can only do this by Friday. 

Greetings,
Mecki

**Comment by MahyaSad** [comment]
Hello everyone,
I have installed pyroSAR successfully using anaconda and my python version is 3.8. However, I cannot import different packages of pyroSAR and get this error:
cannot import name 'geocode' from 'pyroSAR.snap' (unknown location)
cannot import name 'identify' from 'pyroSAR.snap' (unknown location)

Installing pyroSAR has destroyed some of the other packages too.

Is there any solution for solving this problem?

Thanks
Mahya

**Comment by maawoo** [comment]
Hi @MahyaSad!
I assume you installed it as described [here](https://pyrosar.readthedocs.io/en/latest/general/installation.html#conda)? 
Are you using a conda environment and have just forgotten to activate it before trying to import any modules of the package?
If you're not familiar with conda environments, I can recommend [this article](https://towardsdatascience.com/a-guide-to-conda-environments-bc6180fc533). You can for example run the following:
`conda create --name pyrosar_env python=3.7 pyrosar` which creates a conda environment called "pyrosar_env" with Python 3.7 and installs the current version of pyroSAR and its dependencies inside the environment. Afterwards you can activate the environment by running `conda activate pyrosar_env` and shouldn't run into any import issues. 
Hope that helps!

**Comment by ashish-iitb** [comment]
> I'm sure it will. Updating is actually quite easy. Make sure to back up your SNAP configuration files in the etc subfolder of the installation directory though. We had the problem that they were just overwritten without notice messing up our download directories.

Hello, I tried working with PyroSAR with SLC dataset. But it is giving me the error as "correctOSV() missing 1 required positional argument: 'directory'".

My code is :
from pyroSAR import identify
from pyroSAR.gamma import correctOSV
scene = '/home/ashish/Desktop/vegetation_monitoring/data/sar/data_zip/S1B_IW_SLC__1SDV_20190412T003920_20190412T003947_015766_01D978_06AD.zip'
id = identify(scene)
id.unpack('tmpdir')
correctOSV(id=id, osvdir='/home/ashish/Desktop/vegetation_monitoring/data/sar/data_zip/osvdir', osvType='POE')

**Comment by ashish-iitb** [comment]
> Hi @ashish-iitb the function `correctOSV` requires the scene to be converted to GAMMA format. See the documentation here: https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.gamma.correctOSV

Thanks @johntruckenbrodt , I will go through the documentation. My purpose is to form an interferogram using pyrosar. I am working on it. the steps which i am focusing are: read, split, apply orbit file,geocoding, interferogram generation, deburst, goldstein filtering,  multilook and then i will use SNAPHU to export the product to form the interferogram. I read the pyrosar documentation but found a little of these processes. can you help me out figuring these processes. One more thing, I am working with SLC image. But i noticed, pyrosar works with GRD image. are SLC images not compatible with pyrosar. 
Please guide.

**Comment by ashish-iitb** [comment]
> Hi @ashish-iitb the function `correctOSV` requires the scene to be converted to GAMMA format. See the documentation here: https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.gamma.correctOSV

Hello @johntruckenbrodt ,  I followed the documentation but in
`# convert the unpacked scene to GAMMA format`

`convert2gamma(id=scene,directory=scene.scene)`
the output of this comes out to be an error which said
`name 'isp' is not defined`

the upper part of code runs smoothly and gave me the unpack scene directory. 
I am attaching the screenshot too. Please have a look .
![Screenshot from 2022-03-22 12-15-20](https://user-images.githubusercontent.com/63877660/159423826-dca08876-f1b9-49c1-a334-61e385c056c4.png)

Please guide.

**Comment by johntruckenbrodt** [comment]
Looks like you don't have the GAMMA software installed.
