### ISSUE TITLE
class Raster option for reading all bands into a 3D numpy array

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#48]
Currently the method Raster.matrix only returns single bands, by default the first one. It would be more intuitive if the default would be all bands as one array.
This is directly related to the internal band management in Raster.__data, which also needs to be adjusted in this context.

**Comment by ibaris** [comment]
I solve that problem already. In which repository should I add my solution? In pyroSAR?

**Comment by johntruckenbrodt** [comment]
I am currently moving all spatial stuff into the new repo, I should get this done by today. I'll give you a notice once I am ready.

**Comment by johntruckenbrodt** [comment]
This is now possible via spatialist method [Raster.array](https://spatialist.readthedocs.io/en/latest/spatialist.html#spatialist.raster.Raster.array) added in johntruckenbrodt/spatialist@d3431fb965ce52b03722f0dc329a99b4b1e8a7b6
