### ISSUE TITLE
Installation of rasterio as an alternative to raster module.

### ISSUE THREAD

**Issue by ibaris** [johntruckenbrodt/pyroSAR#5]
Today I tried to figure out how rasterio works. The first point is you should install rasterio in a virtual environment. After I follow these several steps gdal and in general [Anaconda](https://www.anaconda.com) won’t work properly, e.g.:
```
>>> import gdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Python27\lib\site-packages\osgeo\__init__.py", line 21, in <mo
    _gdal = swig_import_helper()
  File "C:\Python27\lib\site-packages\osgeo\__init__.py", line 17, in swit_helper
  _mod = imp.load_module('_gdal', fp, pathname, description)
ImportError: DLL load failed: The specified procedure could not be found.
```

So, I must reinstall my python distribution. I don´t know if it is a specific problem with Windows. Even if I install it with conda-forge it did not work due to problems with dependencies.  Can I try the install procedure on our Linux server?

**Comment by johntruckenbrodt** [comment]
I guess this depends how you installed GDAL. The safest bet is to always use the conda installer. In any case you can always modify/create your PYTHONPATH environment variable to ensure any Python distribution finds it. Additonally, we need to discuss in how far we can or want to use rasterio as any software using it must be distributed with the same license. Thus we would not be able to use our MIT license anymore.

**Comment by ibaris** [comment]
Since rasterio package is difficult to install and the implementation of a different raster management system is not urgent, we delay the implementation for later.
