### ISSUE TITLE
outsourcing of spatial tools into separate Python package

### ISSUE THREAD

**Issue by johntruckenbrodt** [johntruckenbrodt/pyroSAR#50]
All this functionality has grown substantially and might also be used outside of the pyroSAR environment. Let's make this easier by providing it in a separate package without all the pyroSAR overkill.

The following steps are yet to be done:
- [x] settle on the final package name
- [x] decide on location of cross-dependency ancillary.py
- [x] set up coveralls
- [x] set up readthedocs
- [x] host package on PyPI
- [x] remove spatial functionality from pyroSAR and import new package instead
- [x] move tests of spatial functionality to new package
- [ ] clean pyroSAR git history
- [ ] integrate all open issues for the spatial tools in pyroSAR into new package

**Comment by johntruckenbrodt** [comment]
mh that's a bit too specific since we want to have a tool for general spatial operations, thus also vector data.
How about spatialist?

**Comment by ibaris** [comment]
Nice one! I hope this name is available on GitHub and PIP. It sounds great :blush:

**Comment by johntruckenbrodt** [comment]
Cool, thanks. Doesn't matter if the name is taken on Github. I just created a dummy repo. Let's get this thing on pypi as soon as possible :-D

**Comment by johntruckenbrodt** [comment]
Okay so the basic move is done. I also moved the git history for all still existing files in the new repo.  
The following steps are yet to be done:
- [ ] settle on the final name for the package
- [ ] set up coveralls for spatialist
- [ ] host spatialist on PyPI
- [ ] remove spatial functionality from pyroSAR and import spatialist instead
- [ ] clean pyroSAR git history

**Comment by johntruckenbrodt** [comment]
THis is an old issue and the spatial components are well integrated into package [spatialist](https://github.com/johntruckenbrodt/spatialist).
