### ISSUE TITLE
Setup appveyor

### ISSUE THREAD

**Issue by felixcremer** [johntruckenbrodt/pyroSAR#52]
At the moment, we are only testing on Linux and MacOS via Travis. 
We should setup appveyor to also automatically test on Windows.

**Comment by johntruckenbrodt** [comment]
Yep, good idea. Would you like to look into it?

**Comment by ibaris** [comment]
I think Jenkins should be a CI for Windows: https://jenkins.io/solutions/github/

**Comment by johntruckenbrodt** [comment]
Yep, that's one option for a Windows CI. [AppVeyor](https://www.appveyor.com/) seems to be more widely used in the open source community though. I got it to run, although the spatialite extension does not work on their system. It does on my local Windows 7 machine though. I merged the branch yesterday, check out the readme badge.
