### ISSUE TITLE
Problems execuding geocode for single polarized S1-Images

### ISSUE THREAD

**Issue by JohannesBalling** [johntruckenbrodt/pyroSAR#59]
Dear Reader,

when I want to pre-process several Sentinel-1 scenes I run into a problem executing the geocode function for single polarized Sentinel-1 Images. See below the Summary of one of the Images (Just for getting an idea of what kind of image I am talking about):

#### Summary of a mentioned Sentinel-1 image (example)

```
S1A_IW_GRDH_1SSV_20150107T230831_20150107T230856_004071_004EB4_B3EC.zip
acquisition_mode: IW
lines: 16882
orbit: A
polarizations: ['VV']
product: GRD
projection: GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]
samples: 26604
sensor: S1A
spacing: (10.0, 9.9913)
start: 20150107T230831
stop: 20150107T230856
['VV']

```

#### Problem description
However, If i want to use the geocode function to pre-process them, I run into following error message.
I have that for several scenes (~70 in total) and all of them are single polarized.

```
S1A_IW_GRDH_1SSV_20150107T230831_20150107T230856_004071_004EB4_B3EC.zip
Executing processing graph
 done.
INFO: org.esa.snap.core.gpf.operators.tooladapter.ToolAdapterIO: Initializing external tool adapters
SEVERE: org.esa.s2tbx.dataio.gdal.activator.GDALDistributionInstaller: The environment variable LD_LIBRARY_PATH is not set. It must contain the current folder '.'.

Error: [NodeId: Calibration] Operator 'CalibrationOp': Value for 'Source Band' is invalid: 'Intensity'

```
Apparently there is something wrong with a non existing source band "Intensity", so I am not to sure whether the problem arises from the script or function itself.

#### Script
See below the straight forward script I am using. Where selection_proc is the selected Archive of Sentinel-1 scenes to be pre-processed.

```
for scene in selection_proc:
	id=identify(scene)
	if id.meta['IPF_version'] < 2.9:
		temp_bn=True
	else:
		temp_bn=False
    	geocode(infile=scene, outdir=outdir, tr=resolution, scaling='db',removeS1BoderNoise=temp_bn)
```

Thank you very much in advance for your help. If you need any additional information do not hesitate to contact me.

Best regards,
Johannes

**Comment by felixcremer** [comment]
What version of pyroSAR are you using?

This should be fixed by https://github.com/johntruckenbrodt/pyroSAR/commit/e7f5d35fcc774f510df10a4f5da48e4b405d2ec3.

**Comment by JohannesBalling** [comment]
I just updated pyroSAR and the pre-processing seems to work now. Thank you very much for your help and greetings to Jena!
