### ISSUE TITLE
geocode_back

### ISSUE THREAD

**Issue by matziel1** [johntruckenbrodt/pyroSAR#80]
I received the following error message while geocoding:

geocoding and normalization..
Traceback (most recent call last):
  File "example_scoop_gamma.py", line 139, in <module>
    results = list(futures.map(worker, sites))
  File "example_scoop_gamma.py", line 119, in worker
    func_geoback=2, func_interp=2, sarSimCC=False, osvdir=osvdir, cleanup=False, allow_RES_OSV=False)
  File "/home/c3urma/repositories/pyroSAR/pyroSAR/gamma/util.py", line 761, in geocode
    shellscript=shellscript)
TypeError: geocode_back() got an unexpected keyword argument 'lookup_table'

**Comment by johntruckenbrodt** [comment]
This error can occur when pyroSAR is used with parsed GAMMA commands from an older version of pyroSAR. Please delete the configuration and parsed commands like this:
`rm -rf $HOME/.pyrosar/*`
Next time you import pyroSAR in Python a new configuration is created and the GAMMA commands are parsed again using the parser of your new installation.
This will be no longer necessary in the next pyroSAR version (0.9).
