### ISSUE TITLE
Issue in downloading orbit files using S1.OSV

### ISSUE THREAD

**Issue by matziel1** [johntruckenbrodt/pyroSAR#82]
searching for new POE files
Traceback (most recent call last):
  File "/home/c3urma/repositories/pyroSAR/pyroSAR/S1/auxil.py", line 197, in catch
    response = urlopen(subaddress, context=self.sslcontext).read().decode('utf-8')
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 500: Internal Server Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example_scoop_gamma.py", line 136, in <module>
    osv.update()
  File "/home/c3urma/repositories/pyroSAR/pyroSAR/S1/auxil.py", line 423, in update
    raise e
  File "/home/c3urma/repositories/pyroSAR/pyroSAR/S1/auxil.py", line 421, in update
    files_poe = self.catch(sensor=['S1A', 'S1B'], osvtype='POE', start=self.maxdate('POE', 'start'))
  File "/home/c3urma/repositories/pyroSAR/pyroSAR/S1/auxil.py", line 200, in catch
    raise RuntimeError(e)
RuntimeError: HTTP Error 500: Internal Server Error

**Comment by johntruckenbrodt** [comment]
This is an error from the remote server. Maybe just try again later

**Comment by matziel1** [comment]
I also thought about that. However, I receive this error since the last few days.
The URL is working in the browser!

**Comment by johntruckenbrodt** [comment]
ah okay. I'll look into it

**Comment by matziel1** [comment]
It seems that it is not working for folder, which are already existing. If I try to save the orbit files into a new folder, the download works.

**Comment by Aranil** [comment]
I've got similar Error message at first:

mod_spatialite: mod_spatialite.so: cannot open shared object file: No such file or directory
mod_spatialite.so: mod_spatialite.so.so: cannot open shared object file: No such file or directory
mod_spatialite.dll: mod_spatialite.dll.so: cannot open shared object file: No such file or directory
loading extension spatialite as libspatialite
using sqlite version 3.7.17
using spatialite version b'4.1.1'
nothing to be done
searching for new POE files
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=1&validity_start=2019-06-03..2019-06-27
---------------------------------------------------------
searching for new RES files
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=1&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=2&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=3&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=4&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=5&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=6&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=7&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=8&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=9&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=10&validity_start=2019-06-03..2019-06-27
Traceback (most recent call last):
  File "/home/se56rij/sarbian/xx_03_processing/sar_processing_gamma_dem_home.py", line 142, in <module>
    osv.update()
  File "/home/se56rij/.local/lib/python3.6/site-packages/pyroSAR/S1/auxil.py", line 437, in update
    self.retrieve(files_res)
  File "/home/se56rij/.local/lib/python3.6/site-packages/pyroSAR/S1/auxil.py", line 376, in retrieve
    infile = urlopen(remote, context=self.sslcontext)
  File "/usr/lib64/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib64/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib64/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib64/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found


After I've deleted already existing folder for 'OSV'-files, 'scenelist.db' and run the skript again, I've got follow Error message:


mod_spatialite: mod_spatialite.so: cannot open shared object file: No such file or directory
mod_spatialite.so: mod_spatialite.so.so: cannot open shared object file: No such file or directory
mod_spatialite.dll: mod_spatialite.dll.so: cannot open shared object file: No such file or directory
loading extension spatialite as libspatialite
using sqlite version 3.7.17
using spatialite version b'4.1.1'
100% (90 of 90) |##################################################################| Elapsed Time: 0:00:06 Time:  0:00:06
90 scenes registered regularly
0 duplicates detected and registered
searching for new POE files
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=1&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=2&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=3&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=4&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=5&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=6&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=7&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=8&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=9&validity_start=2014-07-31..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_poeorb/?page=10&validity_start=2014-07-31..2019-06-27
---------------------------------------------------------
searching for new RES files
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=1&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=2&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=3&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=4&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=5&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=6&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=7&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=8&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=9&validity_start=2019-06-03..2019-06-27
https://qc.sentinel1.eo.esa.int/aux_resorb/?page=10&validity_start=2019-06-03..2019-06-27
deleting 0 RES files
/home/se56rij/.local/lib/python3.6/site-packages/scoop/fallbacks.py:46: RuntimeWarning: SCOOP was not started properly.
Be sure to start your program with the '-m scoop' parameter. You can find further information in the documentation.
Your map call has been replaced by the builtin serial Python map().
  RuntimeWarning
20190607T005942
<class 'spatialist.vector.Vector'>
mod_spatialite: mod_spatialite.so: cannot open shared object file: No such file or directory
mod_spatialite.so: mod_spatialite.so.so: cannot open shared object file: No such file or directory
mod_spatialite.dll: mod_spatialite.dll.so: cannot open shared object file: No such file or directory
loading extension spatialite as libspatialite
using sqlite version 3.7.17
using spatialite version b'4.1.1'
geo01.rz.uni-jena.de: 90 scenes found for site geometry_Polygon
unpacking scene..
removing border noise..
(0, 0, 2000, 16688)
(0, 0, 26402, 2000)
(24402, 0, 26402, 16688)
(0, 14688, 26402, 16688)
converting scene to GAMMA format..
updating orbit state vectors..
orbit state vector correction failed for scene /home/se56rij/sarbian/xx_06_processed/geometry_Polygon/proc_in/S1A_IW_GRDH_1SDV_20170101T165945_20170101T170010_014641_017CE5_8F2F.SAFE


I am trying process  S1 data for year 2017, but script loads OSV(POEORB)-files only for year 2019.

**Comment by johntruckenbrodt** [comment]
Thanks @Aranil for the report. I'll look into it

**Comment by johntruckenbrodt** [comment]
This bug is likely specific to method [OSV.update](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.S1.OSV.update). You can alternatively use methods [OSV.catch](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.S1.OSV.catch) and [OSV.retrieve](https://pyrosar.readthedocs.io/en/latest/pyroSAR.html#pyroSAR.S1.OSV.retrieve) in combination to also have more control over which files are actually downloaded.

**Comment by Aranil** [comment]
I have implemented OSV.catch and OSV.retrieve methods instead of OSV.update method, unfortunately I have got the same result, OSV(POEORB)-files were downloaded only for year 2019.

**Comment by johntruckenbrodt** [comment]
The following worked for me:
```python
from pyroSAR.S1 import OSV
from pyroSAR import identify

filename = 'S1A_IW_GRDH_1SDV_20150222T170750_20150222T170815_004739_005DD8_3768.zip'

id = identify(filename)

osvdir = '/path'

id.getOSV(osvdir)

with OSV(osvdir) as osv:
    files = osv.catch(sensor='S1A', start='20170101T000000', stop='20170101T000000')
    osv.retrieve(files)
```
Can you please check whether these two options work for you?

**Comment by johntruckenbrodt** [comment]
I just fixed a bug which resulted in missing files in the result of `OSV.catch` if the selected time span was very long. A maximum of ten pages was searched, each containing 20 files. Hence, if the search result was longer than 200 files (e.g. for a whole year) not all files were returned.  
This fix is contained in the latest master branch on GitHub. You can find installation instructions in the README.
Does that solve your issue?

**Comment by Aranil** [comment]
Thanks for your reply! yes it solved my issue.
