### ISSUE TITLE
Sigma-nought processing

### ISSUE THREAD

**Issue by system123** [johntruckenbrodt/pyroSAR#84]
As far as I can see there is no way to allow for the output of Sigma0 using PyroSAR (only Beta0 and Gamma0) it would be nice to be able to process to Sigma0 as Google Earth Engine provides this as the default output for Sentiel1 tiles. So any algorithms built on GEE would require Sigma0 products.

**Comment by johntruckenbrodt** [comment]
good point. I'll get into it.

**Comment by johntruckenbrodt** [comment]
It should now be possible to replicate the GEE workflow with
`terrainFlattening=False` and `refarea='sigma0'`
