### ISSUE TITLE
find_datasets has position dependant arguments

### ISSUE THREAD

**Issue by system123** [johntruckenbrodt/pyroSAR#86]
The order the arguments are specified to find_datasets changes the result. The argument order shouldn't matter when filtering datasets.

An example is when I have a directory of S1A and S1B, with pol=VV and VH and A and D orbits, the following two commands result in different file lists.

`find_datasets(self.base_dir, recursive=False, sensor=('S1A', 'S1B'), polarization=("VV", "VH"), orbit="A")`

`find_datasets(self.base_dir, recursive=False, sensor=('S1A', 'S1B'), orbit="A", polarization=("VV", "VH"))`

**Comment by johntruckenbrodt** [comment]
thanks @system123, a fix is under way.
