### ISSUE TITLE
Error cleaning RES orbit files when no POE files

### ISSUE THREAD

**Issue by matthewhanson** [johntruckenbrodt/pyroSAR#91]
Hello, 

I'm running pyroSAR with SNAP on a cluster where it's doing batch processing. The first data file is processed fine, but the next one fails when trying to clean up the RES files.  In this case both files were new, so there were no POE files. The traceback is:

```
File \"/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyroSAR/snap/util.py\", line 160, in geocode\n id.getOSV()\n File \"/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyroSAR/drivers.py\", line 1260, in getOSV\n osv.retrieve(files)\n File \"/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyroSAR/S1/auxil.py\", line 435, in retrieve\n self.clean_res()\n File \"/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyroSAR/S1/auxil.py\", line 298, in clean_res\n deprecated = [x for x in self.getLocals('RES') if self.date(x, 'stop') < maxdate_poe]\n File \"/root/.pyenv/versions/3.6.8/lib/python3.6/site-packages/pyroSAR/S1/auxil.py\", line 298, in <listcomp>\n deprecated = [x for x in self.getLocals('RES') if self.date(x, 'stop') < maxdate_poe]\nTypeError: '<' not supported between instances of 'str' and 'NoneType'\n
```

It looks like the error is because `maxdate_poe` is returning None here:
https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/S1/auxil.py#L312

because there are no POE files, and then it compares it to another date 
https://github.com/johntruckenbrodt/pyroSAR/blob/master/pyroSAR/S1/auxil.py#L272

I may be misreading the code though, as I haven't forked it and done any debugging yet.

**Comment by johntruckenbrodt** [comment]
Hi Matthew,

thanks for reporting the issue. I discovered several issues with the OSV download functionality in the last days and ended up reworking the class quite extensively. So maybe some things got messed up.
I will get back to it tomorrow.

Cheers,
John

**Comment by johntruckenbrodt** [comment]
This should now be fixed with 3a34897.

**Comment by johntruckenbrodt** [comment]
Hi @matthewhanson,
just checking, is this problem fixed so I can close the issue?
Cheers,
John

**Comment by matthewhanson** [comment]
Hi @johntruckenbrodt yes, thanks for checking in, it works with that fix now.
