### ISSUE TITLE
parse_datasetname fails for extra files

### ISSUE THREAD

**Issue by system123** [johntruckenbrodt/pyroSAR#94]
The `parse_datasetname` fails when parsing files related to the `export_extra` argument (i.e. DEM, localIncidenceAngle etc.) It would be nice to be able to group and stack these extra files in the same way as standard polarized bands but to do that parse_datasetname needs to work for creating the stacking groups.

**Comment by johntruckenbrodt** [comment]
good idea, thanks. This should work now.
